---

# Lab 1: NumPy for Investment Analysis

## Learning Objectives
By the end of this lab, you will be able to:
- Create and manipulate NumPy arrays for financial data
- Perform basic statistical calculations on investment returns
- Use array operations to analyze portfolio performance
- Apply NumPy broadcasting for portfolio calculations
- Reshape and aggregate financial data arrays

## Introduction
NumPy is essential for quantitative finance and investment analysis. This lab demonstrates how to use NumPy arrays to work with stock prices, returns, and portfolio data.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Set random seed for reproducible results
np.random.seed(42)

## Exercise 1: Stock Price Arrays
Create NumPy arrays to represent stock price data.

Create a NumPy array 'aapl_prices' with Apple stock prices over 5 days
`Use prices: [150.0, 152.5, 148.0, 155.0, 157.5]`

In [ ]:
aapl_prices = np.array([150.0, 152.5, 148.0, 155.0, 157.5])

Create a 2D array 'portfolio_prices' representing prices for 3 stocks over 4 days
`Row 0: AAPL prices [150, 152, 148, 155]`

`Row 1: MSFT prices [300, 305, 298, 310]`

`Row 2: GOOGL prices [2800, 2850, 2780, 2900]`


In [ ]:
portfolio_prices = np.array([
    [150, 152, 148, 155],
    [300, 305, 298, 310],
    [2800, 2850, 2780, 2900]
])

In [ ]:
print("Apple Stock Prices:", aapl_prices)
print("\nPortfolio Prices:")
print(portfolio_prices)
print("\nArray shapes:")
print(f"AAPL prices shape: {aapl_prices.shape}")
print(f"Portfolio prices shape: {portfolio_prices.shape}")

Apple Stock Prices: [150.  152.5 148.  155.  157.5]

Portfolio Prices:
[[ 150  152  148  155]
 [ 300  305  298  310]
 [2800 2850 2780 2900]]

Array shapes:
AAPL prices shape: (5,)
Portfolio prices shape: (3, 4)


## Exercise 2: Return Calculations
Calculate investment returns using NumPy operations.

Calculate daily returns for AAPL stock

Daily return = (Price_today - Price_yesterday) / Price_yesterday

In [3]:
aapl_returns = (aapl_prices[1:] - aapl_prices[:-1]) / aapl_prices[:-1]

Calculate the total return for AAPL over the period

Total return = (Final_price - Initial_price) / Initial_price

In [4]:
aapl_total_return = (aapl_prices[-1] - aapl_prices[0]) / aapl_prices[0]

Calculate portfolio daily returns for each stock

In [5]:
portfolio_returns = (portfolio_prices[:, 1:] - portfolio_prices[:, :-1]) / portfolio_prices[:, :-1]

In [6]:
print("AAPL Daily Returns:", aapl_returns)
print(f"AAPL Total Return: {aapl_total_return:.4f} or {aapl_total_return*100:.2f}%")
print("\nPortfolio Daily Returns:")
print(portfolio_returns)
print("\nReturn shapes:")
print(f"AAPL daily returns shape: {aapl_returns.shape}")
print(f"Portfolio returns shape: {portfolio_returns.shape}")

AAPL Daily Returns: [ 0.01666667 -0.0295082   0.0472973   0.01612903]
AAPL Total Return: 0.0500 or 5.00%

Portfolio Daily Returns:
[[ 0.01333333 -0.02631579  0.0472973 ]
 [ 0.01666667 -0.02295082  0.04026846]
 [ 0.01785714 -0.0245614   0.04316547]]

Return shapes:
AAPL daily returns shape: (4,)
Portfolio returns shape: (3, 3)


## Exercise 3: Statistical Analysis
Compute key statistical measures for investment analysis.

Calculate mean daily return for AAPL

In [7]:
aapl_mean_return = np.mean(aapl_returns)

Calculate standard deviation (volatility) of AAPL returns


In [8]:
aapl_volatility = np.std(aapl_returns)

Calculate mean returns for each stock in the portfolio

In [9]:
portfolio_mean_returns = np.mean(portfolio_returns, axis = 1)

Calculate volatility for each stock in the portfolio

In [10]:
portfolio_volatility = np.std(portfolio_returns, axis = 1)

Find the stock with highest and lowest average return

In [11]:
best_stock_idx = np.argmax(portfolio_mean_returns)
worst_stock_idx = np.argmin(portfolio_mean_returns)

In [12]:
stock_names = ['AAPL', 'MSFT', 'GOOGL']

print(f"AAPL Mean Daily Return: {aapl_mean_return:.4f} ({aapl_mean_return*100:.2f}%)")
print(f"AAPL Volatility: {aapl_volatility:.4f} ({aapl_volatility*100:.2f}%)")
print("\nPortfolio Statistics:")
for i, stock in enumerate(stock_names):
    print(f"{stock}: Mean Return = {portfolio_mean_returns[i]:.4f} ({portfolio_mean_returns[i]*100:.2f}%), Volatility = {portfolio_volatility[i]:.4f} ({portfolio_volatility[i]*100:.2f}%)")

print(f"\nBest performing stock: {stock_names[best_stock_idx]}")
print(f"Worst performing stock: {stock_names[worst_stock_idx]}")

AAPL Mean Daily Return: 0.0126 (1.26%)
AAPL Volatility: 0.0274 (2.74%)

Portfolio Statistics:
AAPL: Mean Return = 0.0114 (1.14%), Volatility = 0.0301 (3.01%)
MSFT: Mean Return = 0.0113 (1.13%), Volatility = 0.0261 (2.61%)
GOOGL: Mean Return = 0.0122 (1.22%), Volatility = 0.0279 (2.79%)

Best performing stock: GOOGL
Worst performing stock: MSFT


## Exercise 4: Portfolio Weights and Values
Work with portfolio composition and calculate portfolio values.

Define number of shares owned for each stock

In [13]:
shares = np.array([100, 50, 10])  # AAPL, MSFT, GOOGL shares

Calculate portfolio value for each day

Portfolio value = sum of (shares * prices) for each stock

In [14]:
portfolio_values = np.sum(shares.reshape(-1, 1) * portfolio_prices, axis = 0)

Calculate portfolio weights based on initial values

In [15]:
initial_stock_values = shares * portfolio_prices[:, 0]
total_initial_value = np.sum(initial_stock_values)
portfolio_weights = initial_stock_values / total_initial_value

Calculate portfolio daily returns

In [16]:
portfolio_daily_returns = (portfolio_values[1:] - portfolio_values[:-1]) / portfolio_values[:-1]

In [17]:
print("Number of shares:", shares)
print("Portfolio values over time:", portfolio_values)
print("\nInitial stock values:", initial_stock_values)
print("Portfolio weights:", portfolio_weights)
print(f"Weight percentages: AAPL={portfolio_weights[0]*100:.1f}%, MSFT={portfolio_weights[1]*100:.1f}%, GOOGL={portfolio_weights[2]*100:.1f}%")
print("\nPortfolio daily returns:", portfolio_daily_returns)
print(f"Portfolio mean daily return: {np.mean(portfolio_daily_returns):.4f} ({np.mean(portfolio_daily_returns)*100:.2f}%)")

Number of shares: [100  50  10]
Portfolio values over time: [58000 58950 57500 60000]

Initial stock values: [15000 15000 28000]
Portfolio weights: [0.25862069 0.25862069 0.48275862]
Weight percentages: AAPL=25.9%, MSFT=25.9%, GOOGL=48.3%

Portfolio daily returns: [ 0.01637931 -0.02459712  0.04347826]
Portfolio mean daily return: 0.0118 (1.18%)


## Exercise 5: Array Creation Functions
Use NumPy functions to create arrays for financial modeling.

Create a correlation matrix (3x3 identity matrix as placeholder)

In [18]:
correlation_matrix = np.eye(3)

Create an array of equally-weighted portfolio (all weights = 1/3)

In [19]:
equal_weights = np.full(3, 1 / 3)

Create a time array for 252 trading days (1 year)

In [20]:
trading_days = np.arange(1, 253)

Create evenly spaced price levels for a stock chart

In [21]:
price_levels = np.linspace(aapl_prices.min(), aapl_prices.max(), 11)

In [22]:
print("Correlation Matrix:")
print(correlation_matrix)
print("\nEqual weights portfolio:", equal_weights)
print("\nFirst 10 trading days:", trading_days[:10])
print(f"Total trading days: {len(trading_days)}")
print("\nPrice levels for analysis:")
print(price_levels)

Correlation Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Equal weights portfolio: [0.33333333 0.33333333 0.33333333]

First 10 trading days: [ 1  2  3  4  5  6  7  8  9 10]
Total trading days: 252

Price levels for analysis:
[148.   148.95 149.9  150.85 151.8  152.75 153.7  154.65 155.6  156.55
 157.5 ]


## Exercise 6: Advanced Array Indexing
Use advanced indexing to analyze stock performance.

Find days where portfolio returns were positive


In [23]:
positive_return_days = portfolio_daily_returns > 0
positive_returns = portfolio_daily_returns[positive_return_days]

Get the maximum price for each stock


In [24]:
max_prices = np.max(portfolio_prices, axis = 1)

Find the day when each stock reached its maximum price


In [25]:
max_price_days = np.argmax(portfolio_prices, axis = 1)

Create a boolean mask for stocks that had positive average returns


In [26]:
profitable_stocks = portfolio_mean_returns > 0

In [27]:
print("Positive return days:", positive_return_days)
print("Positive returns:", positive_returns)
print(f"Number of positive return days: {np.sum(positive_return_days)}")
print("\nMaximum prices by stock:", max_prices)
print("Days of maximum prices:", max_price_days)
print("\nStocks with positive average returns:", profitable_stocks)
profitable_stock_names = np.array(stock_names)[profitable_stocks]
print("Profitable stock names:", profitable_stock_names)

Positive return days: [ True False  True]
Positive returns: [0.01637931 0.04347826]
Number of positive return days: 2

Maximum prices by stock: [ 155  310 2900]
Days of maximum prices: [3 3 3]

Stocks with positive average returns: [ True  True  True]
Profitable stock names: ['AAPL' 'MSFT' 'GOOGL']


## Exercise 7: Broadcasting and Portfolio Analysis
Use NumPy broadcasting for efficient portfolio calculations.

Calculate normalized prices (divide all prices by initial price)

In [28]:
normalized_prices = portfolio_prices / portfolio_prices[:, 0].reshape(-1, 1)

Add a transaction cost of 0.1% to all returns

In [29]:
transaction_cost = 0.001
net_returns = portfolio_returns - transaction_cost

Calculate weighted portfolio returns using broadcasting

weighted_returns = weights * individual_returns, then sum across stocks

In [30]:
weighted_portfolio_returns = np.sum(portfolio_weights.reshape(-1, 1) * portfolio_returns, axis = 0)

In [31]:
print("Normalized prices (relative to initial price):")
print(normalized_prices)
print("\nNet returns (after transaction costs):")
print(net_returns)
print("\nWeighted portfolio returns:", weighted_portfolio_returns)
print(f"Average weighted portfolio return: {np.mean(weighted_portfolio_returns):.4f} ({np.mean(weighted_portfolio_returns)*100:.2f}%)")

Normalized prices (relative to initial price):
[[1.         1.01333333 0.98666667 1.03333333]
 [1.         1.01666667 0.99333333 1.03333333]
 [1.         1.01785714 0.99285714 1.03571429]]

Net returns (after transaction costs):
[[ 0.01233333 -0.02731579  0.0462973 ]
 [ 0.01566667 -0.02395082  0.03926846]
 [ 0.01685714 -0.0255614   0.04216547]]

Weighted portfolio returns: [ 0.01637931 -0.02459859  0.04348482]
Average weighted portfolio return: 0.0118 (1.18%)


## Exercise 8: Random Portfolio Simulation
Generate random data to simulate portfolio scenarios.

Generate random daily returns for a Monte Carlo simulation

Simulate 1000 scenarios with 30 days each for 3 stocks

In [32]:
num_simulations = 1000
num_days = 30
num_stocks = 3

Generate random returns (normal distribution with mean=0.001, std=0.02)


In [33]:
simulated_returns = np.random.normal(0.001, 0.02, size = (num_simulations, num_days, num_stocks))

Calculate cumulative returns for each simulation

In [34]:
cummulative_returns = np.cumprod(1 + simulated_returns, axis = 1) - 1

Calculate final portfolio values for each simulation

In [35]:
portfolio_final_returns = cummulative_returns[:, -1, :].mean(axis = 1)

In [36]:
print(f"Simulated returns shape: {simulated_returns.shape}")
print(f"Final portfolio returns statistics:")
print(f"Mean: {np.mean(portfolio_final_returns):.4f} ({np.mean(portfolio_final_returns)*100:.2f}%)")
print(f"Std: {np.std(portfolio_final_returns):.4f} ({np.std(portfolio_final_returns)*100:.2f}%)")
print(f"5th percentile (VaR): {np.percentile(portfolio_final_returns, 5):.4f} ({np.percentile(portfolio_final_returns, 5)*100:.2f}%)")
print(f"95th percentile: {np.percentile(portfolio_final_returns, 95):.4f} ({np.percentile(portfolio_final_returns, 95)*100:.2f}%)")

Simulated returns shape: (1000, 30, 3)
Final portfolio returns statistics:
Mean: 0.0316 (3.16%)
Std: 0.0665 (6.65%)
5th percentile (VaR): -0.0790 (-7.90%)
95th percentile: 0.1429 (14.29%)


## Exercise 9: Array Reshaping and Aggregation
Reshape financial data for different analysis perspectives.

Reshape portfolio prices to calculate weekly returns

Assume we have 4 weeks of data (4 days), reshape to (3, 2, 2) for 2 weeks （2 days/week)

In [37]:
weekly_prices = portfolio_prices.reshape(3, 2, 2)

Calculate weekly returns (last day of week vs first day)

In [38]:
weekly_returns = (weekly_prices[:, :, -1] - weekly_prices[:, :, 0]) / weekly_prices[:, :, 0]

Flatten the returns array and calculate overall statistics

In [39]:
all_returns_flat = weekly_prices.flatten()

Create a reshaped view for calculating cross-correlations

In [40]:
returns_reshaped = weekly_returns.reshape(3, 2)

In [41]:
print("Original portfolio prices shape:", portfolio_prices.shape)
print("Weekly prices shape:", weekly_prices.shape)
print("\nWeekly returns:")
print(weekly_returns)
print("\nFlattened returns shape:", all_returns_flat.shape)
print("Flattened returns:", all_returns_flat)
print("Overall return statistics:")
print(f"Mean: {np.mean(all_returns_flat):.4f}")
print(f"Std: {np.std(all_returns_flat):.4f}")
print(f"Min: {np.min(all_returns_flat):.4f}")
print(f"Max: {np.max(all_returns_flat):.4f}")

Original portfolio prices shape: (3, 4)
Weekly prices shape: (3, 2, 2)

Weekly returns:
[[0.01333333 0.0472973 ]
 [0.01666667 0.04026846]
 [0.01785714 0.04316547]]

Flattened returns shape: (12,)
Flattened returns: [ 150  152  148  155  300  305  298  310 2800 2850 2780 2900]
Overall return statistics:
Mean: 1095.6667
Std: 1229.9911
Min: 148.0000
Max: 2900.0000


## Summary

In this lab, you have learned to:

1. **Create and manipulate arrays** for financial data representation
2. **Calculate returns** using vectorized operations
3. **Compute statistical measures** like mean, standard deviation, and percentiles
4. **Work with portfolio data** including weights and values
5. **Use advanced indexing** to filter and analyze data
6. **Apply broadcasting** for efficient calculations
7. **Generate random data** for Monte Carlo simulations
8. **Reshape and aggregate** data for different analysis perspectives

These NumPy skills form the foundation for more advanced financial analysis and portfolio optimization techniques you'll encounter in future labs.