In [2]:
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(42)


In [ ]:
aapl_prices = np.array([150.0, 152.5, 148.0, 155.0, 157.5])

portfolio_prices = np.array([
    [150, 152, 148, 155],
    [300, 305, 298, 310],
    [2800, 2850, 2780, 2900]
])


---

In [6]:
aapl_returns = (aapl_prices[1:] - aapl_prices[:-1]) / aapl_prices[:-1]
print(aapl_returns)

[ 0.01666667 -0.0295082   0.0472973   0.01612903]


In [12]:
aapl_mean_return = np.mean(aapl_returns)
aapl_volatility = np.std(aapl_returns)
print(f"\n {aapl_mean_return * 100:.2f}% \n {aapl_volatility * 100:.2f}%")



 1.26% 
 2.74%


---

In [7]:
portfolio_returns = (portfolio_prices[:, 1:] - portfolio_prices[:, :-1]) / portfolio_prices[:, :-1]
print(portfolio_returns)


[[ 0.01333333 -0.02631579  0.0472973 ]
 [ 0.01666667 -0.02295082  0.04026846]
 [ 0.01785714 -0.0245614   0.04316547]]


In [16]:
portfolio_mean_returns = np.mean(portfolio_returns, axis = 1)
portfolio_volatility = np.std(portfolio_returns, axis = 1)
print(f"\n {portfolio_mean_returns} \n {portfolio_volatility}")



 [0.01143828 0.0113281  0.01215374] 
 [0.03008228 0.02608377 0.02794195]


In [17]:
shares = np.array([100, 50, 10])

In [18]:
portfolio_values = np.sum(shares.reshape(-1, 1) * portfolio_prices, axis = 0)
print(portfolio_values)


[58000 58950 57500 60000]


In [23]:
initial_stock_values = shares * portfolio_prices[:, 0]
total_initial_value = np.sum(initial_stock_values)
portfolio_weights = initial_stock_values / total_initial_value
print(f"{np.round(portfolio_weights * 100, 2)}%")


[25.86 25.86 48.28]%


In [25]:
portfolio_daily_returns = (portfolio_values[1:] - portfolio_values[:-1]) / portfolio_values[:-1]
print(f"{np.round(portfolio_daily_returns * 100, 2)}%")


[ 1.64 -2.46  4.35]%


---

In [27]:
correlation_matrix = np.eye(3)
print(correlation_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
equal_weights = np.full(3, 1 / 3)
print(equal_weights)


[0.33333333 0.33333333 0.33333333]


In [29]:
trading_days = np.arange(1, 253)
print(len(trading_days)
)

252


In [30]:
price_levels = np.linspace(aapl_prices.min(), aapl_prices.max(), 11)
print(price_levels)


[148.   148.95 149.9  150.85 151.8  152.75 153.7  154.65 155.6  156.55
 157.5 ]


---

In [33]:
positive_return_days = portfolio_daily_returns > 0
positive_returns = portfolio_daily_returns[positive_return_days]
print(f"\n {positive_return_days}\n {positive_returns}")



 [ True False  True]
 [0.01637931 0.04347826]


In [34]:
max_prices = np.max(portfolio_prices, axis = 1)
max_price_days = np.argmax(portfolio_prices, axis = 1)
print(f"\n {max_prices}\n {max_price_days}")



 [ 155  310 2900]
 [3 3 3]


In [35]:
profitable_stocks = portfolio_mean_returns > 0
print(profitable_stocks)


[ True  True  True]


In [36]:
normalized_prices = portfolio_prices / portfolio_prices[:, 0].reshape(-1, 1)
print(normalized_prices)


[[1.         1.01333333 0.98666667 1.03333333]
 [1.         1.01666667 0.99333333 1.03333333]
 [1.         1.01785714 0.99285714 1.03571429]]


In [37]:
transaction_cost = 0.001
net_returns = portfolio_returns - transaction_cost
print(net_returns)


[[ 0.01233333 -0.02731579  0.0462973 ]
 [ 0.01566667 -0.02395082  0.03926846]
 [ 0.01685714 -0.0255614   0.04216547]]


In [38]:
weighted_portfolio_returns = np.sum(portfolio_weights.reshape(-1, 1) * portfolio_returns, axis = 0)
print(weighted_portfolio_returns)


[ 0.01637931 -0.02459859  0.04348482]


In [39]:
num_simulations = 1000
num_days = 30
num_stocks = 3


In [ ]:
simulated_returns = np.random.normal(0.001, 0.02, (num_simulations, num_days, num_stocks))


In [42]:
cummulative_returns = np.cumprod(simulated_returns + 1, axis = 1) - 1


In [44]:
portfolio_final_returns = cummulative_returns[:, -1, :].mean(axis = 1)


In [45]:
weekly_prices = portfolio_prices.reshape(3, 2, 2)
print(weekly_prices)


[[[ 150  152]
  [ 148  155]]

 [[ 300  305]
  [ 298  310]]

 [[2800 2850]
  [2780 2900]]]


In [48]:
weekly_returns = (weekly_prices[:, :, -1] - weekly_prices[:, :, 0]) / weekly_prices[:, :, 0]
print(weekly_returns)


[[0.01333333 0.0472973 ]
 [0.01666667 0.04026846]
 [0.01785714 0.04316547]]


In [49]:
all_returns_flat = weekly_returns.flatten()
print(all_returns_flat)


[0.01333333 0.0472973  0.01666667 0.04026846 0.01785714 0.04316547]


In [50]:
returns_reshaped = weekly_returns.reshape(3, 2)
print(returns_reshaped)


[[0.01333333 0.0472973 ]
 [0.01666667 0.04026846]
 [0.01785714 0.04316547]]
